### ISSUE TITLE
Does not boot on macOS 10.15.3

### ISSUE THREAD

**Issue by NBEGnHsx** [miffy/mailpeeper-tls#5]
Does not boot on macOS 10.15.3.
Until macOS 10.15.2, it was unstable but managed to work.

**Comment by NBEGnHsx** [comment]
Dyld Error Message:
  Library not loaded: /usr/local/opt/openssl/lib/libcrypto.1.0.0.dylib
  Referenced from: /Applications/mailpeeper-tls.app/Contents/MacOS/mailpeeper-tls
  Reason: image not found

**Comment by miffy** [comment]
maybe, dylib is old.
This dylib was made with old Homebrew.
The old Homebrew's tools doesn't work in Catalina, and this dylib too.
Do you really want to use it?
If you want it, then I'll fix it. or you can do pull request.

**Comment by NBEGnHsx** [comment]
There is one provider that only supports POP (Plala Light), so I really want to use it.

**Comment by miffy** [comment]
あ〜日本人の方なら日本語でいいっすよｗ。
趣味でしかMac使っていないので、少し時間がかかるかもしれないですけどいいですか？
I'll fix it ,maybe.

**Comment by NBEGnHsx** [comment]
ゆっくりで構いません。ぷららライトのアカウントはめったにメール来ませんし。
あと、今代替で使ってるIMAPのメールチェッカだと、先に別端末でメール読むと既読扱いになってしまうという少々不便なとこがあり、mailpeeper-tlsのほうがいいなと思ってます。

**Comment by miffy** [comment]
ご愛顧ありがとうございます。久しぶりに週末OSSプログラマーに戻りました。
Xcodeのプロジェクトの設定をいじってビルドしなおしたら動くようにはなりました。
（久しぶりにプロバイダメール使ったらサーバがTLSで暗号化対応されていてビビったｗ）
空のOSに入れて動作確認してからGitHubに上げますので、それまでよろしくです。

プロジェクトを全部落としてくるのはしんどそうなので、実行ファイルだけ取れるように
できたと思います。できれば別途ダウンロードできるようにしておきたいと思います。
GitHubの機能なのでできなかったらすいません。おぼろげな記憶で書いてます…。

**Comment by miffy** [comment]
とりあえず実行ファイルだけ置いておきました。
https://github.com/miffy/mailpeeper-tls/releases
mailpeeper-tls.zipでお願いします。

ご存知かとは思いますが、実行時にワーニングが出ますので、「システム環境設定＞セキュリティとプライバシー」から動作許可をしてあげてください。

あと動作確認にまっさらなOSを用意できなかったので（catalinaめ…）、開発環境以外できちんと動作するか確かめられてません。ご面倒ですが不具合がありましたらここでご報告をお願いします。できる限り直します。

**Comment by NBEGnHsx** [comment]
同様にエラーで実行できません。コンソールログには同様に
Exception Type:        EXC_CRASH (SIGABRT)
Exception Codes:       0x0000000000000000, 0x0000000000000000
Exception Note:        EXC_CORPSE_NOTIFY

Termination Reason:    DYLD, [0x1] Library missing

Dyld Error Message:
  Library not loaded: /usr/local/opt/openssl/lib/libcrypto.1.0.0.dylib
  Referenced from: /Applications/mailpeeper-tls.app/Contents/MacOS/mailpeeper-tls
  Reason: image not found
と出ています。同ディレクトリにlibcrypto.1.1.dylib ならあるのですが。

**Comment by miffy** [comment]
ご足労かけてすいません。
同ディレクトリというのは、
/usr/local/opt/openssl/lib/
のことですよね。
恐らくShiN-K-278さんが、Homebrewか何かで入れられていたものを今まで見に行っていたのかもしれません。Dylib自体の設定は直していたのですが、そもそものプロジェクト自体がHomebrew由来のディレクトリを参照していたようです。

ちょっとすぐには直らないかもしれないので、また時間をください。再度、実行ファイルを上げ直しますので、申し訳ありませんが再度動作確認お願いします。

**Comment by miffy** [comment]
お待たせいたしました。度々申し訳ありません。
https://github.com/miffy/mailpeeper-tls/releases/tag/v1.0.7.2
に実行ファイルを上げました。

まっさらなCatalinaで動作させたので、たぶん動くかと思います。
それでもダメなら個別対応になりそうですね。
お手数おかけしますがよろしくおねがいします。

**Comment by NBEGnHsx** [comment]
無事起動し、動くようになりました。ありがとうございます。
